version: "3.1"
services: 
    mysqlDB:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: "mypassword"
            MYSQL_DATABASE: "drupal"
        deploy:
            replicas: 1
            placement:
                constraints:
                - node.labels.region == east-1-d    