apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
    name: wordpress-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpress:5.2-php7.1
              ports:
              - name: http-port
                containerPort: 80
              env:
                - name: WORDPRESS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                       name: wordpress-secrets
                       key: db-password
                - name: WORDPRESS_DB_HOST
                  value: wordpress-db