apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
spec:
  selector:
    matchLabels:
      run: hpa-example
  replicas: 1
  template:
    metadata:
      labels:
        run: hpa-example
    spec:
      containers:
      - name: hpa-example
        image: gcr.io/google_containers/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
    name: hpa-example
spec:
    ports:
    - port: 31010
      nodePort: 31010
      targetPort: http-port
      protocol: TCP
    selector:
        app: hpa-example
    type: NodePort